formatting:
  android: true
  ImportOrdering:
    active: true
  FinalNewline:
    insertFinalNewLine: false
  ParameterListWrapping:
    indentSize: 2

style:
  MagicNumber:
    active: false
  NewLineAtEndOfFile:
    active: false