formatting:
  android: true
  ImportOrdering:
    active: true
  FinalNewline:
    insertFinalNewLine: false
  ParameterListWrapping:
    indentSize: 2

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']

style:
  MagicNumber:
    active: false
  NewLineAtEndOfFile:
    active: false